- title: "Paper Title Number 1"
  date: "2009-10-01"
  venue: "Organometallics"
  authors: "Yumeng Liao, Kohei Takahashi, and Nobuharu Iwasawa"
  image: "/assets/images/paper1.jpg"
  link: "/publication/2009-10-01-paper-title-number-1"

- title: "Paper Title Number 2"
  date: "2012-05-15"
  venue: "Journal of Catalysis"
  authors: "Yumeng Liao, Another Author"
  image: "/assets/images/paper2.jpg"
  link: "/publication/2012-05-15-paper-title-number-2"
